package com.tutorials.mywishlishapp.data

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Represents a wish item in the application.
 *
 * This data class is an Entity for Room persistence library and defines the structure of the "wish-table" database table.
 * Each instance of Wish represents a single wish with a title and an optional description.
 *
 * @property id The unique identifier for the wish. It is auto-generated by the database.
 * @property title The title of the wish. Must be a non-empty string.
 * @property description An optional description providing more details about the wish.
 */
@Entity(tableName = "wish-table")
data class Wish(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    @ColumnInfo(name = "wish-title")
    val title: String = "",
    @ColumnInfo(name = "wish-desc")
    val description: String = "",
)

object DummyWish {
    val wishlist = listOf(
        Wish(title = "Google Watch 2", description = "An android watch"),
        Wish(title = "Google Pixel 7", description = "An android phone"),
        Wish(title = "Google Pixel 6", description = "An android phone"),
        Wish(title = "Bean Bag", description = "A cotton bag for the body")
    )
}